### ISSUE TITLE
Clarification regarding project

### ISSUE THREAD

**Issue by Im-vishalanand** [J-Prajwal/Mini-Projects-OS#3]
Projects which has to be done should be on React only or it can be on JS also.

**Comment by J-Prajwal** [comment]
@Im-vishalanand the projects are supposed to be created only by the tech stacks mentioned. This repo aims to build your understanding and logic on how you approach any problem using advanced libraries/frameworks.

If you want, I can also create some issues, which can be built upon vanilla js, CSS, and HTML. Thanks for showing your interest.
